name: Deploy Game API Reference

on:
  push:
    branches: [main, dev/backend]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy API Reference
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Remove uneed files
        run: rm backend/docs/docs.go backend/docs/swagger.yaml

      - name: Deploy to 2026 repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_2026 }}
          external_repository: sitcon-tw/2026
          publish_branch: build
          publish_dir: ./backend/docs
          destination_dir: game
